"""empty message

Revision ID: 3464419719ef
Revises: d80d2aa573c5
Create Date: 2016-06-10 16:47:48.974094

"""

# revision identifiers, used by Alembic.
revision = '3464419719ef'
down_revision = 'd80d2aa573c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
